### PR TITLE
export both cloneable and Cloneable

### PR DESCRIPTION
**Pull request by MrNghia123**
Now it's backward compatible with current use by exporting both cloneable (default) and Cloneable class.

### CODE REVIEW

**Comment by MrNghia123** [comment]
@mcollina, could you please look at this one?

**Review by mcollina — CHANGES_REQUESTED** [review]
It is not backwards compatible.
I still don't understand what's the goal of this change.

**Comment by MrNghia123** [comment]
The current version does not work with @aws-sdk/client-s3. To be specific, the following code throw error "Expected params.Body to be a string, Buffer, Stream, Blob, or typed array object"

var cloneable = require('cloneable-readable')
var fs = require('fs')

var stream = cloneable(fs.createReadStream('./package.json'))
s3.send(new PutObjectCommand({
      Key: "/test1",
      ACL: 'public-read',
      Body: stream,
      ContentType: 'application/json',
      Bucket: "bucket"
    })
s3.send(new PutObjectCommand({
      Key: "/test2",
      ACL: 'public-read',
      Body: stream.clone(),
      ContentType: 'application/json',
      Bucket: "bucket"
    })

The pull request fixed this error.

**Comment by mcollina** [comment]
Please add a test to reproduce the problem this is fixing.

**Comment by phated** [comment]
It's likely they are doing a naive `instanceof` check against node core streams, which readable-stream wouldn't satisfy. I don't think this change should be made, as readable-stream should be kept.

**Comment by mcollina** [comment]
Agreed. The bug seems to be on the AWS side.

**Pull request closed without merging**
