### PR TITLE
Adds travis jobs on ppc64le

### PR DESCRIPTION
**Pull request by dineshks1**
This PR adds power support on travis.

### CODE REVIEW

**Comment by mcollina** [comment]
why?

**Comment by dineshks1** [comment]
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. for more info @gerrith3.

**Comment by mcollina** [comment]
Given the change Travis had on the free tier, I'm -1. I'm not adding another architecture.

**Comment by gerrith3** [comment]
Hey @mcollina Travis's change didn't really impact open source projects.  They changed to a credit system because they are trying to crack down on bitcoin miners and such using their infrastructure.  You get 10,000 credits to start, and can request more at any time via either email to support@travis-ci.com or filling out their tracking system form (their preferred model) at support.travis-ci.com.  10,000 credits is about 1,000 minutes, you can request the number of credits that match your needs.  This still leaves them at parity with GHA and CircleCI, for instance.

**Pull request closed without merging**
